[workspace]
resolver = "2"
members = [
    "udf-hash",
    "udf-net",
    "udf-jsonify",
    "udf-lipsum",
    "udf-uuid",
    "test-integration",
]

[profile.release]
# Minimize binary size by removing all symbols
strip = "symbols"
codegen-units = 1
lto = "fat"
